In [155]:
from sklearn.metrics import cohen_kappa_score, confusion_matrix, make_scorer, recall_score, f1_score
import numpy as np
import pandas as pd
from collections import Counter
from tqdm import tqdm

In [175]:
predictions = pd.read_csv('unlabeled_predictions.csv')
labels = pd.read_csv("vt_labels.csv").Labels.values.tolist()
labels_1 = pd.read_csv("vt_labels_1.csv").Labels.values.tolist()

In [157]:
def specificity(y_true, y_pred): 
    tn = confusion_matrix(y_true, y_pred)[0, 0]
    fp = confusion_matrix(y_true, y_pred)[0, 1]
    neg = tn + fp
    return tn/neg



In [176]:
len(labels_1)

4578

In [159]:
ht_sd = predictions['Labeled with subdomains'].values.tolist()
ht_nosd = predictions['Labeled w/o subdomains'].values.tolist()
dtc = predictions['Labeled dtc'].values.tolist()
rfc = predictions['Labeled rfc'].values.tolist()
xgb = predictions['Labeled xgb'].values.tolist()
gbc = predictions['Labeled gbc'].values.tolist()
mlp = predictions['Labeled mlp'].values.tolist()
svc = predictions['Labeled svc'].values.tolist()

dtc_sd = predictions['Labeled dtc_sd'].values.tolist()
rfc_sd = predictions['Labeled rfc_sd'].values.tolist()
xgb_sd = predictions['Labeled xgb_sd'].values.tolist()
gbc_sd = predictions['Labeled gbc_sd'].values.tolist()
mlp_sd = predictions['Labeled mlp_sd'].values.tolist()
svc_sd = predictions['Labeled svc_sd'].values.tolist()

In [160]:
predictions.drop('Domain', inplace=True, axis=1)


In [161]:
len(labels)

13453

In [162]:
print(Counter(labels))
print(Counter(ht_sd[:13453]))

Counter({0: 13117, 1: 336})
Counter({0: 12913, 1: 540})


In [177]:
print(Counter(labels_1))
print(Counter(ht_sd[20000:20000+4578]))

Counter({0: 3990, 1: 588})
Counter({0: 3713, 1: 865})


In [163]:
print(specificity(labels, ht_sd[:13453]))
print(recall_score(labels, ht_sd[:13453]))

0.9824655027826484
0.9226190476190477


In [164]:
print(specificity(labels, ht_nosd[:13453]))
print(recall_score(labels, ht_nosd[:13453]))

0.9662270336204924
0.8125


In [165]:
print(specificity(labels, xgb[:13453]))
print(recall_score(labels, xgb[:13453]))

0.990317908058245
0.7023809523809523


In [166]:
print(specificity(labels, xgb_sd[:13453]))
print(recall_score(labels, xgb_sd[:13453]))

0.9909278036136312
0.7470238095238095


In [167]:
confusion_matrix(labels, ht_sd[:13453])

array([[12887,   230],
       [   26,   310]], dtype=int64)

In [168]:
cohen_kappa_score(labels, ht_sd[:13453])

0.6984780529555904

In [169]:
confusion_matrix(labels, ht_nosd[:13453])

array([[12674,   443],
       [   63,   273]], dtype=int64)

In [170]:
confusion_matrix(labels, dtc[:13453])

array([[12940,   177],
       [  126,   210]], dtype=int64)

In [171]:
confusion_matrix(labels, rfc[:13453])

array([[12940,   177],
       [   84,   252]], dtype=int64)

In [172]:
confusion_matrix(labels, xgb[:13453])

array([[12990,   127],
       [  100,   236]], dtype=int64)

In [129]:
confusion_matrix(labels,gbc[:14072])

array([[13454,   270],
       [  198,   150]], dtype=int64)

In [131]:
confusion_matrix(labels, mlp[:14072])

array([[13474,   250],
       [  176,   172]], dtype=int64)

In [132]:
confusion_matrix(labels, svc[:14072])

array([[13343,   381],
       [  180,   168]], dtype=int64)

In [133]:
confusion_matrix(labels, dtc_sd[:14072])

array([[13434,   290],
       [  162,   186]], dtype=int64)

In [134]:
confusion_matrix(labels, rfc_sd[:14072])

array([[13482,   242],
       [  186,   162]], dtype=int64)

In [135]:
confusion_matrix(labels, xgb_sd[:14072])

array([[13499,   225],
       [  188,   160]], dtype=int64)

In [136]:
confusion_matrix(labels, gbc_sd[:14072])

array([[13488,   236],
       [  181,   167]], dtype=int64)

In [138]:
confusion_matrix(labels, mlp_sd[:14072])

array([[13475,   249],
       [  173,   175]], dtype=int64)

In [139]:
confusion_matrix( labels, svc_sd[:14072])

array([[13435,   289],
       [  162,   186]], dtype=int64)

In [53]:
def calc_kappa(y_1, df):
    k_s = []
    for i in df.columns:
        k_s.append(cohen_kappa_score(y_1, df))
    return k_s

In [54]:
kk_1 = []
for i in predictions.columns:
    kk_1.append(cohen_kappa_score(ht_sd, predictions[i].values.tolist()))

kk_1 = pd.Series(kk_1, name='HT_sd')

In [55]:
kk_2 = []
for i in predictions.columns:
    kk_2.append(cohen_kappa_score(ht_nosd, predictions[i].values.tolist()))

kk_2 = pd.Series(kk_2, name='HT_nosd')

In [56]:
kk_3 = []
for i in predictions.columns:
    kk_3.append(cohen_kappa_score(dtc, predictions[i].values.tolist()))
    
kk_3 = pd.Series(kk_3, name='DTC_nosd')

In [57]:
kk_4 = []
for i in predictions.columns:
    kk_4.append(cohen_kappa_score(rfc, predictions[i].values.tolist()))
    
kk_4 = pd.Series(kk_4, name='RFC_nosd')

In [58]:
kk_5 = []
for i in predictions.columns:
    kk_5.append(cohen_kappa_score(xgb, predictions[i].values.tolist()))
kk_5 = pd.Series(kk_5, name='XGB_nosd')

In [59]:
kk_6 = []
for i in predictions.columns:
    kk_6.append(cohen_kappa_score(gbc, predictions[i].values.tolist()))
kk_6 = pd.Series(kk_6, name='GBC_nosd')

In [60]:
kk_7 = []
for i in predictions.columns:
    kk_7.append(cohen_kappa_score(mlp, predictions[i].values.tolist()))
kk_7 = pd.Series(kk_7, name='MLP_nosd')

In [61]:
kk_8 = []
for i in predictions.columns:
    kk_8.append(cohen_kappa_score(svc, predictions[i].values.tolist()))
kk_8 = pd.Series(kk_8, name='SVC_nosd')

In [62]:
kk_9 = []
for i in predictions.columns:
    kk_9.append(cohen_kappa_score(dtc_sd, predictions[i].values.tolist()))
kk_9 = pd.Series(kk_9, name='DTC_sd')

In [63]:
kk_10 = []
for i in predictions.columns:
    kk_10.append(cohen_kappa_score(rfc_sd, predictions[i].values.tolist()))
kk_10 = pd.Series(kk_10, name='RFC_sd')

In [64]:
kk_11 = []
for i in predictions.columns:
    kk_11.append(cohen_kappa_score(xgb_sd, predictions[i].values.tolist()))
kk_11 = pd.Series(kk_11, name='XGB_sd')

In [65]:
kk_12 = []
for i in predictions.columns:
    kk_12.append(cohen_kappa_score(gbc_sd, predictions[i].values.tolist()))
kk_12 = pd.Series(kk_12, name='GBC_sd')

In [66]:
kk_13 = []
for i in predictions.columns:
    kk_13.append(cohen_kappa_score(mlp_sd, predictions[i].values.tolist()))
kk_13 = pd.Series(kk_13, name='MLP_sd')

In [67]:
kk_14 = []
for i in predictions.columns:
    kk_14.append(cohen_kappa_score(svc_sd, predictions[i].values.tolist()))
kk_14 = pd.Series(kk_14, name='SVC_sd')

In [68]:
scores = pd.concat([kk_1, kk_2, kk_3, kk_4, kk_5, kk_6, kk_7, kk_8, kk_9, kk_10, kk_11, kk_12, kk_13, kk_14], axis=1)

In [69]:
i = 0
for j in scores.columns:
    scores.rename(index={i: j}, inplace=True)
    i += 1

In [23]:
# at 10000
scores

HT_sd   HT_nosd  DTC_nosd  RFC_nosd  XGB_nosd  GBC_nosd  \
HT_sd     1.000000  0.472702  0.536007  0.635022  0.641643  0.622850   
HT_nosd   0.472702  1.000000  0.488778  0.538546  0.489606  0.579053   
DTC_nosd  0.536007  0.488778  1.000000  0.676990  0.694215  0.661483   
RFC_nosd  0.635022  0.538546  0.676990  1.000000  0.841810  0.874899   
XGB_nosd  0.641643  0.489606  0.694215  0.841810  1.000000  0.817004   
GBC_nosd  0.622850  0.579053  0.661483  0.874899  0.817004  1.000000   
MLP_nosd  0.759843  0.529465  0.612966  0.761807  0.787290  0.744904   
SVC_nosd  0.602941  0.631339  0.547179  0.725382  0.647358  0.728654   
DTC_sd    0.833846  0.543579  0.646421  0.763219  0.782216  0.747071   
RFC_sd    0.720133  0.457043  0.692239  0.828391  0.838146  0.749378   
XGB_sd    0.717321  0.468487  0.694215  0.808507  0.859107  0.756915   
GBC_sd    0.742215  0.474360  0.676805  0.783177  0.800113  0.754506   
MLP_sd    0.777479  0.515412  0.607393  0.752192  0.771227  0.730170   
SVC_sd    0.833846  0.543579  0.646421  0.763219  0.782216  0.747071   

          MLP_nosd  SVC_nosd    DTC_sd    RFC_sd    XGB_sd    GBC_sd  \
HT_sd     0.759843  0.602941  0.833846  0.720133  0.717321  0.742215   
HT_nosd   0.529465  0.631339  0.543579  0.457043  0.468487  0.474360   
DTC_nosd  0.612966  0.547179  0.646421  0.692239  0.694215  0.676805   
RFC_nosd  0.761807  0.725382  0.763219  0.828391  0.808507  0.783177   
XGB_nosd  0.787290  0.647358  0.782216  0.838146  0.859107  0.800113   
GBC_nosd  0.744904  0.728654  0.747071  0.749378  0.756915  0.754506   
MLP_nosd  1.000000  0.738204  0.919553  0.841608  0.838340  0.883735   
SVC_nosd  0.738204  1.000000  0.711062  0.636694  0.633619  0.660827   
DTC_sd    0.919553  0.711062  1.000000  0.876638  0.873632  0.900143   
RFC_sd    0.841608  0.636694  0.876638  1.000000  0.929761  0.910755   
XGB_sd    0.838340  0.633619  0.873632  0.929761  1.000000  0.901548   
GBC_sd    0.883735  0.660827  0.900143  0.910755  0.901548  1.000000   
MLP_sd    0.960071  0.725705  0.941758  0.860261  0.857017  0.902330   
SVC_sd    0.919553  0.711062  1.000000  0.876638  0.873632  0.900143   

            MLP_sd    SVC_sd  
HT_sd     0.777479  0.833846  
HT_nosd   0.515412  0.543579  
DTC_nosd  0.607393  0.646421  
RFC_nosd  0.752192  0.763219  
XGB_nosd  0.771227  0.782216  
GBC_nosd  0.730170  0.747071  
MLP_nosd  0.960071  0.919553  
SVC_nosd  0.725705  0.711062  
DTC_sd    0.941758  1.000000  
RFC_sd    0.860261  0.876638  
XGB_sd    0.857017  0.873632  
GBC_sd    0.902330  0.900143  
MLP_sd    1.000000  0.941758  
SVC_sd    0.941758  1.000000

In [47]:
# at 100000
scores

HT_sd   HT_nosd  DTC_nosd  RFC_nosd  XGB_nosd  GBC_nosd  MLP_nosd  \
0   1.000000  0.516136  0.432184  0.415136  0.419381  0.430228  0.437489   
1   0.516136  1.000000  0.443471  0.479981  0.486970  0.536886  0.502200   
2   0.432184  0.443471  1.000000  0.827423  0.806695  0.828251  0.792382   
3   0.415136  0.479981  0.827423  1.000000  0.945094  0.889628  0.936006   
4   0.419381  0.486970  0.806695  0.945094  1.000000  0.890612  0.958688   
5   0.430228  0.536886  0.828251  0.889628  0.890612  1.000000  0.897348   
6   0.437489  0.502200  0.792382  0.936006  0.958688  0.897348  1.000000   
7   0.411177  0.501884  0.784041  0.933639  0.942187  0.895415  0.968206   
8   0.462255  0.503385  0.793584  0.932526  0.955771  0.892217  0.981070   
9   0.429417  0.480724  0.811402  0.955144  0.951089  0.882560  0.957973   
10  0.427201  0.483090  0.796100  0.938852  0.967741  0.886212  0.965947   
11  0.419462  0.481268  0.790961  0.927499  0.945158  0.892134  0.963117   
12  0.412326  0.487370  0.783858  0.929843  0.946504  0.887851  0.976667   
13  0.463567  0.504590  0.793200  0.932665  0.956015  0.892810  0.981621   

    SVC_nosd    DTC_sd    RFC_sd    XGB_sd    GBC_sd    MLP_sd    SVC_sd  
0   0.411177  0.462255  0.429417  0.427201  0.419462  0.412326  0.463567  
1   0.501884  0.503385  0.480724  0.483090  0.481268  0.487370  0.504590  
2   0.784041  0.793584  0.811402  0.796100  0.790961  0.783858  0.793200  
3   0.933639  0.932526  0.955144  0.938852  0.927499  0.929843  0.932665  
4   0.942187  0.955771  0.951089  0.967741  0.945158  0.946504  0.956015  
5   0.895415  0.892217  0.882560  0.886212  0.892134  0.887851  0.892810  
6   0.968206  0.981070  0.957973  0.965947  0.963117  0.976667  0.981621  
7   1.000000  0.962278  0.948731  0.949315  0.959145  0.966051  0.963634  
8   0.962278  1.000000  0.963519  0.968080  0.966525  0.968473  0.998595  
9   0.948731  0.963519  1.000000  0.964808  0.956999  0.955690  0.963613  
10  0.949315  0.968080  0.964808  1.000000  0.960244  0.961476  0.967921  
11  0.959145  0.966525  0.956999  0.960244  1.000000  0.964863  0.966416  
12  0.966051  0.968473  0.955690  0.961476  0.964863  1.000000  0.969076  
13  0.963634  0.998595  0.963613  0.967921  0.966416  0.969076  1.000000

In [70]:
# at 350000 (original)
scores

HT_sd   HT_nosd  DTC_nosd  RFC_nosd  XGB_nosd  GBC_nosd  \
HT_sd     1.000000  0.380922  0.223846  0.219961  0.230166  0.205385   
HT_nosd   0.380922  1.000000  0.168401  0.182236  0.189823  0.174776   
DTC_nosd  0.223846  0.168401  1.000000  0.840180  0.833158  0.772407   
RFC_nosd  0.219961  0.182236  0.840180  1.000000  0.925738  0.858297   
XGB_nosd  0.230166  0.189823  0.833158  0.925738  1.000000  0.843979   
GBC_nosd  0.205385  0.174776  0.772407  0.858297  0.843979  1.000000   
MLP_nosd  0.251964  0.196362  0.801836  0.897131  0.915568  0.848544   
SVC_nosd  0.234591  0.194510  0.786061  0.890813  0.892551  0.852477   
DTC_sd    0.282199  0.206367  0.796798  0.879436  0.899669  0.825274   
RFC_sd    0.249172  0.196916  0.817793  0.912516  0.916257  0.817670   
XGB_sd    0.247880  0.197348  0.808683  0.898605  0.930267  0.821906   
GBC_sd    0.247925  0.199779  0.803868  0.878642  0.896692  0.826516   
MLP_sd    0.250202  0.202501  0.786245  0.875025  0.892036  0.823985   
SVC_sd    0.283565  0.206662  0.796271  0.879449  0.899631  0.825561   

          MLP_nosd  SVC_nosd    DTC_sd    RFC_sd    XGB_sd    GBC_sd  \
HT_sd     0.251964  0.234591  0.282199  0.249172  0.247880  0.247925   
HT_nosd   0.196362  0.194510  0.206367  0.196916  0.197348  0.199779   
DTC_nosd  0.801836  0.786061  0.796798  0.817793  0.808683  0.803868   
RFC_nosd  0.897131  0.890813  0.879436  0.912516  0.898605  0.878642   
XGB_nosd  0.915568  0.892551  0.899669  0.916257  0.930267  0.896692   
GBC_nosd  0.848544  0.852477  0.825274  0.817670  0.821906  0.826516   
MLP_nosd  1.000000  0.945947  0.957674  0.925052  0.928809  0.931833   
SVC_nosd  0.945947  1.000000  0.934562  0.907943  0.906774  0.917559   
DTC_sd    0.957674  0.934562  1.000000  0.952813  0.950820  0.956459   
RFC_sd    0.925052  0.907943  0.952813  1.000000  0.962518  0.948853   
XGB_sd    0.928809  0.906774  0.950820  0.962518  1.000000  0.948519   
GBC_sd    0.931833  0.917559  0.956459  0.948853  0.948519  1.000000   
MLP_sd    0.956917  0.937460  0.967228  0.942135  0.943166  0.951119   
SVC_sd    0.958294  0.935943  0.998285  0.952739  0.950903  0.956594   

            MLP_sd    SVC_sd  
HT_sd     0.250202  0.283565  
HT_nosd   0.202501  0.206662  
DTC_nosd  0.786245  0.796271  
RFC_nosd  0.875025  0.879449  
XGB_nosd  0.892036  0.899631  
GBC_nosd  0.823985  0.825561  
MLP_nosd  0.956917  0.958294  
SVC_nosd  0.937460  0.935943  
DTC_sd    0.967228  0.998285  
RFC_sd    0.942135  0.952739  
XGB_sd    0.943166  0.950903  
GBC_sd    0.951119  0.956594  
MLP_sd    1.000000  0.967868  
SVC_sd    0.967868  1.000000